<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.ImageField(upload_to=''),
        ),
    ]
=======
# Generated by Django 5.1.6 on 2025-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.ImageField(upload_to=''),
        ),
    ]
>>>>>>> e7df23b (second commit)
